/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jav_correctionBackend_document_Token_CandIterator */

#ifndef _Included_jav_correctionBackend_document_Token_CandIterator
#define _Included_jav_correctionBackend_document_Token_CandIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jav_correctionBackend_document_Token_CandIterator
 * Method:    getCandidatePointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_document_Token_00024CandIterator_getCandidatePointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jav_correctionBackend_document_Token_CandIterator
 * Method:    getNextItemPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_document_Token_00024CandIterator_getNextItemPointer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
