/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jav_correctionBackend_document_Document */

#ifndef _Included_jav_correctionBackend_document_Document
#define _Included_jav_correctionBackend_document_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    getTokenPointer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_document_Document_getTokenPointer
  (JNIEnv *, jobject, jint);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    getPagePointer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_document_Document_getPagePointer
  (JNIEnv *, jobject, jint);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    getNrOfTokens
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Document_getNrOfTokens
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    getNrOfPages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Document_getNrOfPages
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    native_eraseToken
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Document_native_1eraseToken
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Document_clear
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    saveAs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Document_saveAs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    native_saveAsPlaintext
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Document_native_1saveAsPlaintext
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jav_correctionBackend_document_Document
 * Method:    native_saveAsPageSeparatedPlaintext
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Document_native_1saveAsPageSeparatedPlaintext
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
