/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jav_correctionBackend_document_Candidate */

#ifndef _Included_jav_correctionBackend_document_Candidate
#define _Included_jav_correctionBackend_document_Candidate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jav_correctionBackend_document_Candidate
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Candidate_getStr
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Candidate
 * Method:    getInterpretation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Candidate_getInterpretation
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Candidate
 * Method:    getDlev
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jav_correctionBackend_document_Candidate_getDlev
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Candidate
 * Method:    getFrequency
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jav_correctionBackend_document_Candidate_getFrequency
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
