/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jav_correctionBackend_candidateExtractor_CandidateExtractor */

#ifndef _Included_jav_correctionBackend_candidateExtractor_CandidateExtractor
#define _Included_jav_correctionBackend_candidateExtractor_CandidateExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jav_correctionBackend_candidateExtractor_CandidateExtractor
 * Method:    initNativeCandExtractor
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_candidateExtractor_CandidateExtractor_initNativeCandExtractor
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     jav_correctionBackend_candidateExtractor_CandidateExtractor
 * Method:    destroyNativeCandExtractor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_candidateExtractor_CandidateExtractor_destroyNativeCandExtractor
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_candidateExtractor_CandidateExtractor
 * Method:    nativeQuery
 * Signature: (Ljava/lang/String;ILjav/correctionBackend/candidateExtractor/CandidateReceiver;)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_candidateExtractor_CandidateExtractor_nativeQuery
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     jav_correctionBackend_candidateExtractor_CandidateExtractor
 * Method:    nativeLookup
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jav_correctionBackend_candidateExtractor_CandidateExtractor_nativeLookup
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
