/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jav_correctionBackend_CandidateSet */

#ifndef _Included_jav_correctionBackend_CandidateSet
#define _Included_jav_correctionBackend_CandidateSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jav_correctionBackend_CandidateSet
 * Method:    native_constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_CandidateSet_native_1constructor
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_CandidateSet
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_CandidateSet_native_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_CandidateSet
 * Method:    getNrOfCandidates
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_CandidateSet_getNrOfCandidates
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_CandidateSet
 * Method:    getCandidatePointer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_CandidateSet_getCandidatePointer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
