/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jav_correctionBackend_document_Token */

#ifndef _Included_jav_correctionBackend_document_Token
#define _Included_jav_correctionBackend_document_Token
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getImageFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Token_getImageFileName
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    setWCorr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Token_setWCorr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getWCorr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Token_getWCorr
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getWDisplay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Token_getWDisplay
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getWOCR
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Token_getWOCR
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getWOCR_lc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Token_getWOCR_1lc
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getTopCandidatePointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_document_Token_getTopCandidatePointer
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    isCorrected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jav_correctionBackend_document_Token_isCorrected
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    setCorrected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Token_setCorrected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    isSuspicious
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jav_correctionBackend_document_Token_isSuspicious
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    isNormal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jav_correctionBackend_document_Token_isNormal
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getIndexInDocument
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_getIndexInDocument
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getPageIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_getPageIndex
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getNrOfCandidates
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_document_Token_getNrOfCandidates
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    hasTokenImageInfoBox
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jav_correctionBackend_document_Token_hasTokenImageInfoBox
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    native_handleSplit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_native_1handleSplit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    native_mergeHyphenation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jav_correctionBackend_document_Token_native_1mergeHyphenation
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    mergeLeft
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_mergeLeft
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    native_mergeRight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_native_1mergeRight__
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    native_mergeRight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_native_1mergeRight__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getCandItemPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jav_correctionBackend_document_Token_getCandItemPointer
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getCoordinate_left
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_getCoordinate_1left
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getCoordinate_right
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_getCoordinate_1right
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getCoordinate_top
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_getCoordinate_1top
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Token
 * Method:    getCoordinate_bottom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Token_getCoordinate_1bottom
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
