/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jav_correctionBackend_document_Page */

#ifndef _Included_jav_correctionBackend_document_Page
#define _Included_jav_correctionBackend_document_Page
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jav_correctionBackend_document_Page
 * Method:    getImageFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jav_correctionBackend_document_Page_getImageFile
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Page
 * Method:    getOffsetBegin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Page_getOffsetBegin
  (JNIEnv *, jobject);

/*
 * Class:     jav_correctionBackend_document_Page
 * Method:    getOffsetEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jav_correctionBackend_document_Page_getOffsetEnd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
