# - Find CSL
# Find CSL
#  CSL_INCLUDE_DIR, where to find the headers
#  CSL_LIBRARIES, where to find the libraries
#  CSL_FOUND, If false, do not try to use CSL.


MESSAGE(STATUS "CSL_FIND_REQUIRED is: ${CSL_FIND_REQUIRED}")

FIND_PATH(CSL_INCLUDE_DIR csl/Global.h
 /usr/local/include
 /usr/include
 ${USER_SOFTWARE_DIRS}/include
)


MESSAGE(STATUS "CSL_INCLUDE_DIR is: ${CSL_INCLUDE_DIR}")


SET(CSL_NAMES ${CSL_NAMES} CSL)
FIND_LIBRARY(CSL_LIBRARY
  NAMES ${CSL_NAMES}
  PATHS /usr/lib /usr/local/lib  ${USER_SOFTWARE_DIRS}/lib
  )

MESSAGE(STATUS " CSL_LIBRARY is: ${CSL_LIBRARY}")

IF ( CSL_LIBRARY AND CSL_INCLUDE_DIR )
  SET(CSL_LIBRARIES ${CSL_LIBRARY})
  SET( CSL_FOUND TRUE )
ENDIF ( CSL_LIBRARY AND CSL_INCLUDE_DIR )


IF (CSL_FOUND)
   IF (NOT CSL_FIND_QUIETLY)
      MESSAGE(STATUS "Found CSL: ${CSL_LIBRARIES}")
   ENDIF (NOT CSL_FIND_QUIETLY)
ELSE (CSL_FOUND)
  IF (CSL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find CSL library")
  ELSIF (CSL_FIND_REQUIRED)
    MESSAGE(STATUS "Could not find CSL library (not required)")
  ENDIF (CSL_FIND_REQUIRED)
ENDIF (CSL_FOUND)

MARK_AS_ADVANCED(
  CSL_LIBRARIES
  CSL_INCLUDE_DIR
)



