# - Find Xerces
#  XERCES_INCLUDE_DIR, where to find the headers
#  XERCES_LIBRARIES, where to find the libraries
#  CSL_FOUND, If false, do not try to use CSL.


MESSAGE(STATUS "XERCES_FIND_REQUIRED is: ${XERCES_FIND_REQUIRED}")

FIND_PATH(XERCES_INCLUDE_DIR xercesc/sax/Parser.hpp
# /usr/local/include
# /usr/include
 ${USER_SOFTWARE_DIR}/include
)


MESSAGE(STATUS "XERCES_INCLUDE_DIR is: ${XERCES_INCLUDE_DIR}")


FIND_LIBRARY(XERCES_LIBRARIES
  NAMES xerces-c
  PATHS /usr/lib /usr/local/lib  ${USER_SOFTWARE_DIRS}/lib
  )

MESSAGE(STATUS " XERCES_LIBRARIES is: ${XERCES_LIBRARIES}")

IF ( XERCES_LIBRARIES AND XERCES_INCLUDE_DIR )
  SET( XERCES_FOUND TRUE )
ENDIF ( XERCES_LIBRARIES AND XERCES_INCLUDE_DIR )


IF (XERCES_FOUND)
   IF (NOT XERCES_FIND_QUIETLY)
      MESSAGE(STATUS "Found XERCES: ${XERCES_LIBRARIES}")
   ENDIF (NOT XERCES_FIND_QUIETLY)
ELSE (XERCES_FOUND)
  IF (XERCES_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find XERCES library")
  ELSIF (XERCES_FIND_REQUIRED)
    MESSAGE(STATUS "Could not find XERCES library (not required)")
  ENDIF (XERCES_FIND_REQUIRED)
ENDIF (XERCES_FOUND)

MARK_AS_ADVANCED(
  XERCES_LIBRARIES
  XERCES_INCLUDE_DIR
)

